2024-07-29 18:56:53,154 INFO: Attempting to connect to the database... [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:28]
2024-07-29 18:56:53,154 ERROR: Database connection failed [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:33]
Traceback (most recent call last):
  File "/home/jblancaflor/take-home-proj/zealthy/app/__init__.py", line 30, in create_app
    db.session.execute(text('SELECT 1'))
NameError: name 'text' is not defined
2024-07-29 18:57:29,957 INFO: Application startup [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:67]
2024-07-29 18:57:29,958 INFO: Database URL: sqlite:///dev.db [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:20]
2024-07-29 18:57:29,967 INFO: Application startup [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:27]
2024-07-29 18:57:29,967 INFO: Attempting to connect to the database... [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:29]
2024-07-29 18:57:29,976 INFO: Database connection successful [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:32]
2024-07-29 19:25:29,519 INFO: Application startup [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:67]
2024-07-29 19:25:29,520 INFO: Database URL: sqlite:///dev.db [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:20]
2024-07-29 19:25:29,529 INFO: Application startup [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:27]
2024-07-29 19:25:29,530 INFO: Attempting to connect to the database... [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:29]
2024-07-29 19:25:29,532 INFO: Database connection successful [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:32]
2024-07-29 19:25:39,179 INFO: Application startup [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:67]
2024-07-29 19:25:39,179 INFO: Database URL: sqlite:///dev.db [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:20]
2024-07-29 19:25:39,194 INFO: Application startup [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:27]
2024-07-29 19:25:39,194 INFO: Attempting to connect to the database... [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:29]
2024-07-29 19:25:39,197 INFO: Database connection successful [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:32]
2024-07-29 19:25:53,910 INFO: Application startup [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:67]
2024-07-29 19:25:53,910 INFO: Database URL: sqlite:///dev.db [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:20]
2024-07-29 19:25:53,923 INFO: Application startup [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:27]
2024-07-29 19:25:53,923 INFO: Attempting to connect to the database... [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:29]
2024-07-29 19:25:53,925 INFO: Database connection successful [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:32]
2024-07-29 19:27:44,626 INFO: Application startup [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:67]
2024-07-29 19:27:45,133 INFO: Application startup [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:67]
2024-07-29 19:35:37,952 INFO: Application startup [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:68]
2024-07-29 19:39:47,840 INFO: Application startup [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:69]
2024-07-29 19:45:11,843 INFO: Application startup [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:32]
2024-07-29 19:45:36,101 INFO: Application startup [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:32]
2024-07-29 19:46:04,591 INFO: Application startup [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:32]
2024-07-29 19:46:10,103 INFO: Application startup [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:32]
2024-07-29 19:46:13,842 INFO: Application startup [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:32]
2024-07-29 19:49:24,031 INFO: Application startup [in /home/jblancaflor/take-home-proj/zealthy/app/__init__.py:32]
